version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 3
    registries:
      - github-private

registries:
  github-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.ORG_DEPENDABOT_PAT_READ_PACKAGES}}
