language: go

go:
  - "1.16.2"

install:
  - go install golang.org/x/lint/golint@latest

script:
  - go list ./... | xargs -n1 golint -set_exit_status
  - go test ./...

branches:
  only:
    - master
